import Layout from "@/components/Shared/Layout";
import "@/styles/globals.css";
import { Metadata } from "next";
import type { AppProps } from "next/app";
import { poppins } from "@/lib/fonts";
import { useEffect } from "react";
import useUserState from "@/core/useStore";

import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "StudentHubX",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/toaster"
export default function App({ Component, pageProps }: AppProps) {
  const setUserAsync = useUserState((state) => state.setUserAsync);

  useEffect(() => {
    setUserAsync();
  }, []);

  return (
    <div >
      <Layout className="">
        <Component {...pageProps} />;
      </Layout>
      <Toaster />
    </div>
  );
}
